---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app: movietime
    app.kubernetes.io/name: movietime
  name: movietime
  namespace: default
spec:
  ingressClassName: internal-ingress
  rules:
  - host: movietime.drp.devtest.aws.scania.com
    http:
      paths:
      - backend:
          service:
            name: movietime
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: movietime
  name: movietime
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: movietime
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movietime
  name: movietime
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movietime
  template:
    metadata:
      labels:
        app: movietime
    spec:
      containers:
      - image: <your repo>/movie-library:1.0.0
        name: movie-library
        env:
        # - name: MONGODB_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongodb
        #       key: mongodb-root-password
        - name: MONGODB_URI
          value: "mongodb://mongodb/movies"
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 5m
            memory: 128Mi
          limits:
            cpu: 15m
            memory: 256Mi
...